# Generated by Django 6.0.2 on 2026-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_profile_bio_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='recipe_images/'),
        ),
    ]
