# Generated by Django 6.0.2 on 2026-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
